on:
  push:
    branches:
      - master
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
  build:
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v -o f1viewer-${{ matrix.goos }}-${{ matrix.goarch }} .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}
          path: f1viewer-${{ matrix.goos }}-${{ matrix.goarch }}
